### ISSUE TITLE
RDPC Tenant/Project in Collaboratory 

### ISSUE THREAD

**Issue by andricDu** [icgc-argo/workflow-infra#1]
We need a dedicated openstack project for running the ARGO RDPC

## Detailed Description
- New Project
- 500 Cores
- Alex, Alexis, Dusan, Jared, Henrich as users
- Name can be ARGO-RDPC or w/e Christina prefers

## Extras
Consider slicing off some specific hosts in a host aggregate for performance or isolation related reasons.

**Comment by jmimico** [comment]
Created project ARGO_RDPC_Yung

- Quotas set for 500 cores, 2.3TB RAM, 4.9TB of volumes, 5 floating IP's
- Added users to project as requested
- I've isolated 1 compute host for a NFS server but I think for the time being we will allow the VM's of this project to grab from the general pool of hosts. I would advise using server groups with anti-affinity rules to prevent self made contention/bottlenecks.
